name: Generate CSV and Parquet Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # You can use any version that works for your script

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyarrow  # Install pandas and pyarrow for Parquet support

      # Step 4: Clean the target folder (remove previous generated files)
      - name: Clean target folder
        run: |
          rm -rf target/*  # Remove all files in the 'target' folder

      # Step 5: Run the Python script to generate the CSV and Parquet files
      - name: Run Python script
        run: |
          python ./parquet/generateCsvForIngestion.py  # Make sure this script is located in the root of your repository

      # Step 6: Upload generated files (optional - if you want to store the generated files as artifacts)
      - name: Upload CSV and Parquet files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: |
            ./target/*.csv
            ./target/*.parquet
