name: Upload File to Repository

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: "File to upload (e.g., input.csv)"
        required: true
        type: string
      folder_name:
        description: "Folder to upload to (e.g., data/)"
        required: false
        default: "data"
        type: string

jobs:
  upload-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Folder (if not exists)
        run: mkdir -p ${{ github.event.inputs.folder_name }}

      - name: Upload File (Example: input.csv)
        run: |
          echo "This is a test file for GitHub Actions" > ${{ github.event.inputs.folder_name }}/${{ github.event.inputs.file_name }}

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.event.inputs.folder_name }}/${{ github.event.inputs.file_name }}
          git commit -m "Added ${{ github.event.inputs.file_name }} to ${{ github.event.inputs.folder_name }}"
          git push origin main
